directories:
  output: release/
  buildResources: build
appId: com.aprilfour.gnd
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
      - src/assets/logo.ico
win:
  icon: src/assets/logo.ico
  target:
    - nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: src/assets/logo.ico
  uninstallerIcon: src/assets/logo.ico
  uninstallDisplayName: GND
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: GND
electronVersion: 30.2.0
