# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: gnd-app/package-lock.json

    - name: Install Chrome
      run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

    - run: |
        cd gnd-app
        npm ci
    - run: |
        cd gnd-app
        npm test -- --watch=false --browsers=ChromeHeadless

    # - name: Generate frontend coverage report
    #   run: |
    #     cd gnd-app
    #     npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

    # - name: Move frontend coverage to backend
    #   run: |
    #     mv gnd-app/coverage/lcov.info backend/.coverage.frontend
